import { Metadata } from "next";
import "./styles.css";

// components
import Left from "@/components/left-content";

export const metadata: Metadata = {
	title: {
		absolute: '',
		default: "Kaki Kagatan",
		template: "%s | Kaki Kagatan",
	},
	description: 'Generated by Next.js',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body>
				<Left />
				<div className="
				ml-[12.5rem]
				">
					{children}
				</div>
			</body>
		</html>
	)
}
